[project]
name = "pallanguzhi"
version = "0.1.0"
requires-python = "==3.13.7"
dependencies = [
    "numpy==2.3.2",
    "texttable==1.7.0",
    "torch==2.8.0",
]

[tool.uv]
dev-dependencies = [
    "ruff==0.12.11",
    "pytest==8.4.2",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
