[project]
name = "pallanguzhi"
version = "0.1.0"
requires-python = "==3.14.0"
dependencies = [
    "numpy==2.3.4",
    "texttable==1.7.0",
    "torch==2.9.1",
]

[dependency-groups]
dev = [
    "ruff==0.14.5",
    "pytest==9.0.1",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
