[project]
name = "pallanguzhi"
version = "0.1.0"
requires-python = "==3.14.1"
dependencies = [
    "numpy==2.3.5",
    "texttable==1.7.0",
    "torch==2.9.1",
]

[dependency-groups]
dev = [
    "ruff==0.14.8",
    "pytest==9.0.2",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
