[project]
name = "pallanguzhi"
version = "0.1.0"
requires-python = "==3.14.2"
dependencies = [
    "numpy==2.4.1",
    "texttable==1.7.0",
    "torch==2.10.0",
]

[dependency-groups]
dev = [
    "ruff==0.14.13",
    "pytest==9.0.2",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
