name: UV CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Install dependencies
      run: uv sync

    - name: Run tests
      run: uv run pytest -v

    - name: Train AI
      run: |-
        mkdir -p build
        uv run src/train.py

    - name: Package
      run: |-
        mkdir -p site
        tar czvf site/pallanguzhi.tar.gz src/* build/*.pth pyproject.toml uv.lock

    - name: Create docsite
      run: >-
        docker run \
            -u $(id -u):$(id -g) \
            -v $PWD:/documents/ \
            asciidoctor/docker-asciidoctor:1.80 \
            asciidoctor \
                -D docs \
                --backend=html5 \
                -o /documents/site/index.html \
                /documents/docs/index.adoc

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        force_orphan: true
      if: github.ref == 'refs/heads/main'