name: UV CI
permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Install dependencies
      run: uv sync

    - name: Run tests
      run: uv run pytest -v

    - name: Install ty
      run: uv tool install ty@latest

    - name: Run type checks
      run: uv tool run ty check

    - name: Lint Code
      run: uvx ruff check

    - name: Train AI
      run: |-
        mkdir -p build
        uv run src/train.py

    - name: Package
      run: |-
        mkdir -p site
        tar czvf site/pallanguzhi.tar.gz src/* build/*.pth pyproject.toml uv.lock

    - name: Generate docsite
      id: adocbuild
      uses: tonynv/asciidoctor-action@v2
      with:
          program: "asciidoctor --backend=html5 -o site/index.html docs/index.adoc"

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        force_orphan: true
      if: github.ref == 'refs/heads/main'